targets:
  $default:
    builders:
      riverpod_generator:
        enabled: true
      freezed:
        enabled: true
      json_serializable:
        enabled: true
      i18n:
        enabled: true
    sources:
      - lib/**
      - $package$